name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
#tesr
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
          path: ./codebase/rdicidr-0.1.0
      - run: ls
      - run: npm install --force
        working-directory: ./codebase/rdicidr-0.1.0
      - run: npm run lint
        working-directory: ./codebase/rdicidr-0.1.0
      - run: npm install -g prettier
      - run: npm run prettier
        working-directory: ./codebase/rdicidr-0.1.0
      - run: npm run test
        working-directory: ./codebase/rdicidr-0.1.0
      - run: npm run build
        working-directory: ./codebase/rdicidr-0.1.0 
      - name: Generate deployment package
        working-directory: ./codebase/rdicidr-0.1.0
        run: zip -r deploy.zip * .[^.]* -x "**node_modules**"
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time

      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'

      - name: Beanstalk Deploy for app
        uses: einaregilsson/beanstalk-deploy@v16
        with:
          aws_access_key: ${{secrets.ACCESS_KEY_ID}}
          aws_secret_key: ${{secrets.SECRET_ACCESS_KEY}}
          application_name: nodejs
          environment_name: Nodejs-env
          region: us-east-2
          version_label: "version-label-${{ steps.format-time.outputs.replaced }}"
          deployment_package: ./codebase/rdicidr-0.1.0/deploy.zip
