name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
#tesr
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.node-version }}
      - run: ls
      - name: Reconfigure git to use HTTP authentication
        run: >
          git config --global url."https://github.com/jmugisha3/group-8/".insteadOf
          ssh://git@github.com/
      - run: npm install codebase/rdicidr-0.1.0
      - run: npm run lint
      - run: npm run prettier
      - run: npm run test
      - run: npm run build 
